# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_template.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainTabs(object):
    def setupUi(self, MainTabs):
        MainTabs.setObjectName("MainTabs")
        MainTabs.resize(1321, 836)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainTabs.sizePolicy().hasHeightForWidth())
        MainTabs.setSizePolicy(sizePolicy)
        MainTabs.setMinimumSize(QtCore.QSize(0, 300))
        MainTabs.setMaximumSize(QtCore.QSize(16777215, 836))
        MainTabs.setTabPosition(QtWidgets.QTabWidget.South)
        MainTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_activate = QtWidgets.QWidget()
        self.tab_activate.setObjectName("tab_activate")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_activate)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.tab_activate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_btc = QtWidgets.QCheckBox(self.frame)
        self.checkBox_btc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_btc.setChecked(True)
        self.checkBox_btc.setObjectName("checkBox_btc")
        self.gridLayout_2.addWidget(self.checkBox_btc, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMaxVisibleItems(4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 525, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 7, 1)
        self.checkBox_labs = QtWidgets.QCheckBox(self.frame)
        self.checkBox_labs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_labs.setObjectName("checkBox_labs")
        self.gridLayout_2.addWidget(self.checkBox_labs, 0, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setTextFormat(QtCore.Qt.RichText)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 5, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.frame)
        self.comboBox_8.setMaxVisibleItems(4)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_8, 0, 6, 1, 1)
        self.checkBox_eth = QtWidgets.QCheckBox(self.frame)
        self.checkBox_eth.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_eth.setChecked(True)
        self.checkBox_eth.setObjectName("checkBox_eth")
        self.gridLayout_2.addWidget(self.checkBox_eth, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setTextFormat(QtCore.Qt.RichText)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setMaxVisibleItems(4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.checkBox_zec = QtWidgets.QCheckBox(self.frame)
        self.checkBox_zec.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_zec.setObjectName("checkBox_zec")
        self.gridLayout_2.addWidget(self.checkBox_zec, 1, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setTextFormat(QtCore.Qt.RichText)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 1, 5, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.frame)
        self.comboBox_9.setMaxVisibleItems(4)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_9, 1, 6, 1, 1)
        self.checkBox_kmd = QtWidgets.QCheckBox(self.frame)
        self.checkBox_kmd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_kmd.setChecked(True)
        self.checkBox_kmd.setObjectName("checkBox_kmd")
        self.gridLayout_2.addWidget(self.checkBox_kmd, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setTextFormat(QtCore.Qt.RichText)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 2, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setMaxVisibleItems(4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 2, 2, 1, 1)
        self.checkBox_rick = QtWidgets.QCheckBox(self.frame)
        self.checkBox_rick.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_rick.setObjectName("checkBox_rick")
        self.gridLayout_2.addWidget(self.checkBox_rick, 2, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setTextFormat(QtCore.Qt.RichText)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 2, 5, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.frame)
        self.comboBox_11.setMaxVisibleItems(4)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_11, 2, 6, 1, 1)
        self.checkBox_bch = QtWidgets.QCheckBox(self.frame)
        self.checkBox_bch.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_bch.setObjectName("checkBox_bch")
        self.gridLayout_2.addWidget(self.checkBox_bch, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setTextFormat(QtCore.Qt.RichText)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setMaxVisibleItems(4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_4, 3, 2, 1, 1)
        self.checkBox_morty = QtWidgets.QCheckBox(self.frame)
        self.checkBox_morty.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_morty.setObjectName("checkBox_morty")
        self.gridLayout_2.addWidget(self.checkBox_morty, 3, 4, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setTextFormat(QtCore.Qt.RichText)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 3, 5, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.frame)
        self.comboBox_14.setMaxVisibleItems(4)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_14, 3, 6, 1, 1)
        self.checkBox_doge = QtWidgets.QCheckBox(self.frame)
        self.checkBox_doge.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_doge.setObjectName("checkBox_doge")
        self.gridLayout_2.addWidget(self.checkBox_doge, 4, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setTextFormat(QtCore.Qt.RichText)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 4, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame)
        self.comboBox_5.setMaxVisibleItems(4)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_5, 4, 2, 1, 1)
        self.checkBox_dai = QtWidgets.QCheckBox(self.frame)
        self.checkBox_dai.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_dai.setObjectName("checkBox_dai")
        self.gridLayout_2.addWidget(self.checkBox_dai, 4, 4, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setTextFormat(QtCore.Qt.RichText)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 4, 5, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.frame)
        self.comboBox_12.setMaxVisibleItems(4)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_12, 4, 6, 1, 1)
        self.checkBox_dash = QtWidgets.QCheckBox(self.frame)
        self.checkBox_dash.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_dash.setObjectName("checkBox_dash")
        self.gridLayout_2.addWidget(self.checkBox_dash, 5, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setTextFormat(QtCore.Qt.RichText)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 5, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame)
        self.comboBox_6.setMaxVisibleItems(4)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_6, 5, 2, 1, 1)
        self.checkBox_rvn = QtWidgets.QCheckBox(self.frame)
        self.checkBox_rvn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_rvn.setObjectName("checkBox_rvn")
        self.gridLayout_2.addWidget(self.checkBox_rvn, 5, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setTextFormat(QtCore.Qt.RichText)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 5, 5, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.frame)
        self.comboBox_13.setMaxVisibleItems(4)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_13, 5, 6, 1, 1)
        self.checkBox_ltc = QtWidgets.QCheckBox(self.frame)
        self.checkBox_ltc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ltc.setObjectName("checkBox_ltc")
        self.gridLayout_2.addWidget(self.checkBox_ltc, 6, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setTextFormat(QtCore.Qt.RichText)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 6, 1, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.frame)
        self.comboBox_7.setMaxVisibleItems(4)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_7, 6, 2, 1, 1)
        self.checkBox_bat = QtWidgets.QCheckBox(self.frame)
        self.checkBox_bat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_bat.setObjectName("checkBox_bat")
        self.gridLayout_2.addWidget(self.checkBox_bat, 6, 4, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setTextFormat(QtCore.Qt.RichText)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 6, 5, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.frame)
        self.comboBox_10.setMaxVisibleItems(4)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_10, 6, 6, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.lbl_activate = QtWidgets.QLabel(self.tab_activate)
        self.lbl_activate.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_activate.sizePolicy().hasHeightForWidth())
        self.lbl_activate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_activate.setFont(font)
        self.lbl_activate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_activate.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_activate.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_activate.setObjectName("lbl_activate")
        self.gridLayout.addWidget(self.lbl_activate, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_activate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        MainTabs.addTab(self.tab_activate, "")
        self.tab_balances = QtWidgets.QWidget()
        self.tab_balances.setObjectName("tab_balances")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_balances)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.tab_balances)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3.addWidget(self.frame_4, 0, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.tab_balances)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_balances)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 4, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_balances)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(550, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(550, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3.addWidget(self.frame_3, 2, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.tab_balances)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(600, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(600, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(400, 0, 201, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        self.label_38.setGeometry(QtCore.QRect(210, 0, 181, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_36 = QtWidgets.QLabel(self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(20, 0, 181, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.frame_2, 2, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_balances)
        self.tableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(191)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(110)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(58)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(39)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 5)
        MainTabs.addTab(self.tab_balances, "")
        self.tab_myorders = QtWidgets.QWidget()
        self.tab_myorders.setObjectName("tab_myorders")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_myorders)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.tab_myorders)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_6.addWidget(self.frame_8, 0, 1, 1, 3)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_myorders)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setProperty("showDropIndicator", False)
        self.tableWidget_2.setDragDropOverwriteMode(False)
        self.tableWidget_2.setRowCount(16)
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(179)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_6.addWidget(self.tableWidget_2, 1, 0, 1, 5)
        self.frame_10 = QtWidgets.QFrame(self.tab_myorders)
        self.frame_10.setMinimumSize(QtCore.QSize(930, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_6.addWidget(self.frame_10, 2, 0, 1, 2)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_6.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_6.addWidget(self.pushButton_7, 2, 3, 1, 2)
        MainTabs.addTab(self.tab_myorders, "")
        self.tab_mytrades = QtWidgets.QWidget()
        self.tab_mytrades.setObjectName("tab_mytrades")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_mytrades)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_44 = QtWidgets.QLabel(self.tab_mytrades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.tab_mytrades)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7.addWidget(self.frame_9, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_mytrades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_mytrades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setProperty("showDropIndicator", False)
        self.tableWidget_3.setDragDropOverwriteMode(False)
        self.tableWidget_3.setRowCount(16)
        self.tableWidget_3.setColumnCount(8)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(152)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget_3.verticalHeader().setHighlightSections(True)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_7.addWidget(self.tableWidget_3, 1, 0, 1, 3)
        MainTabs.addTab(self.tab_mytrades, "")
        self.tab_orderbook = QtWidgets.QWidget()
        self.tab_orderbook.setObjectName("tab_orderbook")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_orderbook)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_45 = QtWidgets.QLabel(self.tab_orderbook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 0, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.tab_orderbook)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_8.addWidget(self.frame_11, 0, 1, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_orderbook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_4.sizePolicy().hasHeightForWidth())
        self.tableWidget_4.setSizePolicy(sizePolicy)
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setProperty("showDropIndicator", False)
        self.tableWidget_4.setDragDropOverwriteMode(False)
        self.tableWidget_4.setRowCount(16)
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setObjectName("tableWidget_4")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(207)
        self.tableWidget_4.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.tableWidget_4.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget_4.verticalHeader().setHighlightSections(True)
        self.tableWidget_4.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_8.addWidget(self.tableWidget_4, 1, 0, 1, 3)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_orderbook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_8.addWidget(self.pushButton_10, 2, 2, 1, 1)
        MainTabs.addTab(self.tab_orderbook, "")
        self.tab_wallet = QtWidgets.QWidget()
        self.tab_wallet.setObjectName("tab_wallet")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_wallet)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.tab_wallet)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 560))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 560))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.gridLayout_5.addWidget(self.frame_7, 0, 0, 2, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_wallet)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_39 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_2.addWidget(self.label_39)
        self.label_43 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_2.addWidget(self.label_43)
        self.gridLayout_5.addWidget(self.frame_6, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_wallet)
        self.label_40.setMinimumSize(QtCore.QSize(300, 300))
        self.label_40.setMaximumSize(QtCore.QSize(300, 300))
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 0, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_wallet)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 1, 1, 1, 2)
        self.frame_5 = QtWidgets.QFrame(self.tab_wallet)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_41 = QtWidgets.QLabel(self.frame_5)
        self.label_41.setMinimumSize(QtCore.QSize(250, 40))
        self.label_41.setMaximumSize(QtCore.QSize(250, 40))
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(650, 40))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_42 = QtWidgets.QLabel(self.frame_5)
        self.label_42.setMinimumSize(QtCore.QSize(250, 40))
        self.label_42.setMaximumSize(QtCore.QSize(250, 40))
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(650, 40))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.gridLayout_5.addWidget(self.frame_5, 2, 0, 1, 3)
        MainTabs.addTab(self.tab_wallet, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_config)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_activate_2 = QtWidgets.QLabel(self.tab_config)
        self.lbl_activate_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_activate_2.sizePolicy().hasHeightForWidth())
        self.lbl_activate_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_activate_2.setFont(font)
        self.lbl_activate_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_activate_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_activate_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_activate_2.setObjectName("lbl_activate_2")
        self.gridLayout_4.addWidget(self.lbl_activate_2, 0, 0, 1, 1)
        self.frame_mm2json = QtWidgets.QFrame(self.tab_config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_mm2json.sizePolicy().hasHeightForWidth())
        self.frame_mm2json.setSizePolicy(sizePolicy)
        self.frame_mm2json.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mm2json.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mm2json.setObjectName("frame_mm2json")
        self.formLayout = QtWidgets.QFormLayout(self.frame_mm2json)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.frame_mm2json)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.textEdit = QtWidgets.QTextEdit(self.frame_mm2json)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_13 = QtWidgets.QLabel(self.frame_mm2json)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_mm2json)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_14 = QtWidgets.QLabel(self.frame_mm2json)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_mm2json)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_mm2json)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.label_19 = QtWidgets.QLabel(self.frame_mm2json)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_mm2json)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_20 = QtWidgets.QLabel(self.frame_mm2json)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_mm2json)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_21 = QtWidgets.QLabel(self.frame_mm2json)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_mm2json)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.label_11 = QtWidgets.QLabel(self.frame_mm2json)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox = QtWidgets.QSpinBox(self.frame_mm2json)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.pushButton = QtWidgets.QPushButton(self.frame_mm2json)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.gridLayout_4.addWidget(self.frame_mm2json, 1, 0, 1, 1)
        MainTabs.addTab(self.tab_config, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_log)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_activate_3 = QtWidgets.QLabel(self.tab_log)
        self.lbl_activate_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_activate_3.sizePolicy().hasHeightForWidth())
        self.lbl_activate_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_activate_3.setFont(font)
        self.lbl_activate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_activate_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_activate_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_activate_3.setObjectName("lbl_activate_3")
        self.verticalLayout.addWidget(self.lbl_activate_3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_log)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        MainTabs.addTab(self.tab_log, "")

        self.retranslateUi(MainTabs)
        MainTabs.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(3)
        self.comboBox_8.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(2)
        self.comboBox_9.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(1)
        self.comboBox_11.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)
        self.comboBox_14.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        self.comboBox_12.setCurrentIndex(0)
        self.comboBox_6.setCurrentIndex(0)
        self.comboBox_13.setCurrentIndex(0)
        self.comboBox_7.setCurrentIndex(0)
        self.comboBox_10.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainTabs)

    def retranslateUi(self, MainTabs):
        _translate = QtCore.QCoreApplication.translate
        MainTabs.setWindowTitle(_translate("MainTabs", "TabWidget"))
        self.checkBox_btc.setText(_translate("MainTabs", "Bitcoin"))
        self.label_9.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/btc.svg\"/></p></body></html>"))
        self.comboBox.setCurrentText(_translate("MainTabs", "Buy & sell"))
        self.comboBox.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_labs.setText(_translate("MainTabs", "Labs"))
        self.label_29.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/KMD_Labs_Logo_thick_outline_2_32.png\"/></p></body></html>"))
        self.comboBox_8.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_8.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_8.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_8.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_8.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_eth.setText(_translate("MainTabs", "Ethereum"))
        self.label_22.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/eth.svg\"/></p></body></html>"))
        self.comboBox_2.setCurrentText(_translate("MainTabs", "Sell"))
        self.comboBox_2.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_2.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_2.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_2.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_zec.setText(_translate("MainTabs", "Zcash"))
        self.label_31.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/zec.png\"/></p></body></html>"))
        self.comboBox_9.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_9.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_9.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_9.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_9.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_kmd.setText(_translate("MainTabs", "Komodo"))
        self.label_23.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/kmd.png\"/></p></body></html>"))
        self.comboBox_3.setCurrentText(_translate("MainTabs", "Buy"))
        self.comboBox_3.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_3.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_3.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_3.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_rick.setText(_translate("MainTabs", "Rick"))
        self.label_34.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/kmd.png\"/></p></body></html>"))
        self.comboBox_11.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_11.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_11.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_11.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_11.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_bch.setText(_translate("MainTabs", "Bitcoin Cash"))
        self.label_24.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/bch.png\"/></p></body></html>"))
        self.comboBox_4.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_4.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_4.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_4.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_4.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_morty.setText(_translate("MainTabs", "Morty"))
        self.label_28.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/kmd.png\"/></p></body></html>"))
        self.comboBox_14.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_14.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_14.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_14.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_14.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_doge.setText(_translate("MainTabs", "Dogecoin"))
        self.label_25.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/doge.svg\"/></p></body></html>"))
        self.comboBox_5.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_5.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_5.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_5.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_5.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_dai.setText(_translate("MainTabs", "DAI"))
        self.label_33.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/dai.svg\"/></p></body></html>"))
        self.comboBox_12.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_12.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_12.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_12.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_12.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_dash.setText(_translate("MainTabs", "Dash"))
        self.label_26.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/dash.png\"/></p></body></html>"))
        self.comboBox_6.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_6.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_6.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_6.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_6.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_rvn.setText(_translate("MainTabs", "Raven"))
        self.label_30.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/rvn.svg\"/></p></body></html>"))
        self.comboBox_13.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_13.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_13.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_13.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_13.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_ltc.setText(_translate("MainTabs", "Litecoin"))
        self.label_27.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/ltc.svg\"/></p></body></html>"))
        self.comboBox_7.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_7.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_7.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_7.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_7.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.checkBox_bat.setText(_translate("MainTabs", "BAT"))
        self.label_32.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/bat.svg\"/></p></body></html>"))
        self.comboBox_10.setCurrentText(_translate("MainTabs", "View only"))
        self.comboBox_10.setItemText(0, _translate("MainTabs", "View only"))
        self.comboBox_10.setItemText(1, _translate("MainTabs", "Buy"))
        self.comboBox_10.setItemText(2, _translate("MainTabs", "Sell"))
        self.comboBox_10.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.lbl_activate.setText(_translate("MainTabs", "Select coins for activation"))
        self.pushButton_2.setText(_translate("MainTabs", "Update and activate"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_activate), _translate("MainTabs", "Activate"))
        self.label.setText(_translate("MainTabs", "<html><head/><body><p><span style=\" font-size:16pt;\">Wallet Balances</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainTabs", "Export"))
        self.label_37.setText(_translate("MainTabs", "$777.77"))
        self.label_38.setText(_translate("MainTabs", "0.07"))
        self.label_36.setText(_translate("MainTabs", "Totals:"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Coin"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Address"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Market Price"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainTabs", "Balance"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainTabs", "BTC Value"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainTabs", "USD Value"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_balances), _translate("MainTabs", "Balances"))
        self.label_2.setText(_translate("MainTabs", "<html><head/><body><p><span style=\" font-size:16pt;\">Open Orders</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainTabs", "Export"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Sell Coin"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Sell Vol"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Buying"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainTabs", "Buy Vol"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainTabs", "Sell Price"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainTabs", "Mkt Price"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainTabs", "Premium"))
        self.pushButton_8.setText(_translate("MainTabs", "Cancel Selected"))
        self.pushButton_7.setText(_translate("MainTabs", "Cancel All"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_myorders), _translate("MainTabs", "My Orders"))
        self.label_44.setText(_translate("MainTabs", "<html><head/><body><p><span style=\" font-size:16pt;\">Trade History</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainTabs", "Export"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Date"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Sell Coin"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Sell Vol"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainTabs", "Buy Coin"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainTabs", "Buy Vol"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainTabs", "Sell Price"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainTabs", "Mkt Price"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainTabs", "Profit USD"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_mytrades), _translate("MainTabs", "My Trades"))
        self.label_45.setText(_translate("MainTabs", "<html><head/><body><p><span style=\" font-size:16pt;\">Orderbook</span></p></body></html>"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Sell Coin"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Sell Vol"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Buy Coin"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainTabs", "Buy Vol"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainTabs", "Sell Price"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainTabs", "Mkt Price"))
        self.pushButton_10.setText(_translate("MainTabs", "Buy Selected"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_orderbook), _translate("MainTabs", "Orderbook"))
        self.label_10.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/LABS_wallet.png\"/></p></body></html>"))
        self.label_6.setText(_translate("MainTabs", "LABS"))
        self.label_39.setText(_translate("MainTabs", "777.77"))
        self.label_43.setText(_translate("MainTabs", "$762.99 USD"))
        self.label_40.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/qr_300.png\"/></p></body></html>"))
        self.label_35.setText(_translate("MainTabs", "<html><head/><body><p> Address: <a href=\"https://labs.explorer.dexstats.info/address/R9ViegsR8qrthx81NJdANfnkLoQxomzHAM\"><span style=\" text-decoration: underline; color:#0000ff;\">R9ViegsR8qrthx81NJdANfnkLoQxomzHAM</span></a></p></body></html>"))
        self.label_41.setText(_translate("MainTabs", "Recipient Address:"))
        self.label_42.setText(_translate("MainTabs", "Amount"))
        self.pushButton_4.setText(_translate("MainTabs", "Send"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_wallet), _translate("MainTabs", "Wallet"))
        self.lbl_activate_2.setText(_translate("MainTabs", "Antara Marketmaker Settings"))
        self.label_12.setText(_translate("MainTabs", "Wallet Seed"))
        self.label_13.setText(_translate("MainTabs", "RPC Password"))
        self.label_14.setText(_translate("MainTabs", "RPC IP address"))
        self.lineEdit_2.setPlaceholderText(_translate("MainTabs", "127.0.0.1"))
        self.checkBox.setText(_translate("MainTabs", "Local only"))
        self.label_19.setText(_translate("MainTabs", "Binance API key"))
        self.label_20.setText(_translate("MainTabs", "Binance Secret key"))
        self.label_21.setText(_translate("MainTabs", "Trade Premium (%)"))
        self.label_11.setText(_translate("MainTabs", "NetID"))
        self.pushButton.setText(_translate("MainTabs", "Save"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_config), _translate("MainTabs", "Config"))
        self.lbl_activate_3.setText(_translate("MainTabs", "Antara Marketmaker Console Logs"))
        self.plainTextEdit.setPlainText(_translate("MainTabs", "27 15:28:54, mm2:160] AtomicDEX MarketMaker 2.0.1438_mm2_5df6b0434_Linux\n"
"27 15:28:54, lp_native_dex:1197] version: 2.0.1438_mm2_5df6b0434_Linux\n"
"27 15:28:54, lp_native_dex:1255] lp_init] Trying to fetch the real IP from \'http://checkip.amazonaws.com/\' ...\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:15175\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:51298\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:2859\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:65446\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:43764\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:62104\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:46327\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:17349\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 1.127.111.125:35879\n"
"27 15:28:55, lp_native_dex:1293] IP 1.127.111.125 doesn\'t check: lp_native_dex:1167] http_fallback:300] error creating server listener: Cannot assign requested address (os error 99)\n"
"27 15:28:55, lp_native_dex:1163] test_ip] Trying to listen on 0.0.0.0:15175\n"
"27 15:28:55, lp_native_dex:1180] test_ip] Checking http://127.0.0.1:15175/test_ip\n"
"😅 2019-10-27 23:28:55 +0800 [myipaddr] We couldn\'t bind on the external IP 1.127.111.125, so NAT is likely to be present. We\'ll be okay though.\n"
"… 2019-10-27 23:28:55 +0800 [seed_connection 195.201.116.176:47772] Connecting…\n"
"27 15:28:55, peers:1396] initialize] netid 9999 public key 47b09cea99637eb713fc4a82fe67283dc01f9080f6119089dddeb6d6b1f780f1 preferred port 47773 drill false\n"
"27 15:28:55, rpc:387] >>>>>>>>>> DEX stats 127.0.0.1:7783 DEX stats API enabled at unixtime.1572190135 <<<<<<<<<\n"
"⚡ 2019-10-27 23:28:56 +0800 [seed_connection 195.201.116.176:47772] Connected\n"
"… 2019-10-27 23:28:56 +0800 [seed_connection 46.4.87.18:47772] Connecting…\n"
"⚡ 2019-10-27 23:28:56 +0800 [seed_connection 46.4.87.18:47772] Connected\n"
"… 2019-10-27 23:28:56 +0800 [seed_connection 46.4.78.11:47772] Connecting…\n"
"⚡ 2019-10-27 23:28:56 +0800 [seed_connection 46.4.78.11:47772] Connected\n"
"27 15:28:57, peers:1174] external_ip_alert: 1.127.111.125\n"
"27 15:28:57, peers:1174] external_ip_alert: 1.127.111.125\n"
"27 15:28:57, peers:1174] external_ip_alert: 1.127.111.125\n"
"· 2019-10-27 23:28:58 +0800 [dht-boot] DHT bootstrap ... Done.\n"
"27 16:22:02, peers:1174] external_ip_alert: 2001:8004:16c0:9e7:be45:7060:4073:9b6b\n"
"27 16:22:02, peers:1174] external_ip_alert: 2001:8004:16c0:9e7:be45:7060:4073:9b6b\n"
"27 16:22:02, peers:1174] external_ip_alert: 2001:8004:16c0:9e7:be45:7060:4073:9b6b\n"
"27 16:25:07, peers:1174] external_ip_alert: 1.127.111.125\n"
""))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_log), _translate("MainTabs", "Logs"))

zimport coin_icons_rc
