# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'makerbot_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainTabs(object):
    def setupUi(self, MainTabs):
        MainTabs.setObjectName("MainTabs")
        MainTabs.resize(1721, 836)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainTabs.sizePolicy().hasHeightForWidth())
        MainTabs.setSizePolicy(sizePolicy)
        MainTabs.setMinimumSize(QtCore.QSize(0, 300))
        MainTabs.setMaximumSize(QtCore.QSize(16777215, 878))
        MainTabs.setTabPosition(QtWidgets.QTabWidget.South)
        MainTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_activate = QtWidgets.QWidget()
        self.tab_activate.setObjectName("tab_activate")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_activate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_activate = QtWidgets.QLabel(self.tab_activate)
        self.title_activate.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_activate.sizePolicy().hasHeightForWidth())
        self.title_activate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title_activate.setFont(font)
        self.title_activate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_activate.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.title_activate.setAlignment(QtCore.Qt.AlignCenter)
        self.title_activate.setObjectName("title_activate")
        self.verticalLayout.addWidget(self.title_activate)
        self.frame = QtWidgets.QFrame(self.tab_activate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_btc = QtWidgets.QCheckBox(self.frame)
        self.checkBox_btc.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sml/img/32/color/btc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_btc.setIcon(icon)
        self.checkBox_btc.setChecked(False)
        self.checkBox_btc.setObjectName("checkBox_btc")
        self.gridLayout.addWidget(self.checkBox_btc, 0, 0, 1, 1)
        self.btc_combo = QtWidgets.QComboBox(self.frame)
        self.btc_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.btc_combo.setMaxVisibleItems(4)
        self.btc_combo.setObjectName("btc_combo")
        self.btc_combo.addItem("")
        self.btc_combo.addItem("")
        self.btc_combo.addItem("")
        self.btc_combo.addItem("")
        self.gridLayout.addWidget(self.btc_combo, 0, 1, 1, 1)
        self.btc_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.btc_status.setPalette(palette)
        self.btc_status.setObjectName("btc_status")
        self.gridLayout.addWidget(self.btc_status, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 525, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 3, 7, 1)
        self.checkBox_labs = QtWidgets.QCheckBox(self.frame)
        self.checkBox_labs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_labs.setObjectName("checkBox_labs")
        self.gridLayout.addWidget(self.checkBox_labs, 0, 4, 1, 1)
        self.labs_combo = QtWidgets.QComboBox(self.frame)
        self.labs_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.labs_combo.setMaxVisibleItems(4)
        self.labs_combo.setObjectName("labs_combo")
        self.labs_combo.addItem("")
        self.labs_combo.addItem("")
        self.labs_combo.addItem("")
        self.labs_combo.addItem("")
        self.gridLayout.addWidget(self.labs_combo, 0, 5, 1, 1)
        self.labs_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labs_status.setPalette(palette)
        self.labs_status.setObjectName("labs_status")
        self.gridLayout.addWidget(self.labs_status, 0, 6, 1, 1)
        self.checkBox_eth = QtWidgets.QCheckBox(self.frame)
        self.checkBox_eth.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_eth.setChecked(False)
        self.checkBox_eth.setObjectName("checkBox_eth")
        self.gridLayout.addWidget(self.checkBox_eth, 1, 0, 1, 1)
        self.eth_combo = QtWidgets.QComboBox(self.frame)
        self.eth_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.eth_combo.setMaxVisibleItems(4)
        self.eth_combo.setObjectName("eth_combo")
        self.eth_combo.addItem("")
        self.eth_combo.addItem("")
        self.eth_combo.addItem("")
        self.eth_combo.addItem("")
        self.gridLayout.addWidget(self.eth_combo, 1, 1, 1, 1)
        self.eth_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.eth_status.setPalette(palette)
        self.eth_status.setObjectName("eth_status")
        self.gridLayout.addWidget(self.eth_status, 1, 2, 1, 1)
        self.checkBox_zec = QtWidgets.QCheckBox(self.frame)
        self.checkBox_zec.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_zec.setObjectName("checkBox_zec")
        self.gridLayout.addWidget(self.checkBox_zec, 1, 4, 1, 1)
        self.zec_combo = QtWidgets.QComboBox(self.frame)
        self.zec_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.zec_combo.setMaxVisibleItems(4)
        self.zec_combo.setObjectName("zec_combo")
        self.zec_combo.addItem("")
        self.zec_combo.addItem("")
        self.zec_combo.addItem("")
        self.zec_combo.addItem("")
        self.gridLayout.addWidget(self.zec_combo, 1, 5, 1, 1)
        self.zec_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.zec_status.setPalette(palette)
        self.zec_status.setObjectName("zec_status")
        self.gridLayout.addWidget(self.zec_status, 1, 6, 1, 1)
        self.checkBox_kmd = QtWidgets.QCheckBox(self.frame)
        self.checkBox_kmd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_kmd.setChecked(False)
        self.checkBox_kmd.setObjectName("checkBox_kmd")
        self.gridLayout.addWidget(self.checkBox_kmd, 2, 0, 1, 1)
        self.kmd_combo = QtWidgets.QComboBox(self.frame)
        self.kmd_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.kmd_combo.setMaxVisibleItems(4)
        self.kmd_combo.setObjectName("kmd_combo")
        self.kmd_combo.addItem("")
        self.kmd_combo.addItem("")
        self.kmd_combo.addItem("")
        self.kmd_combo.addItem("")
        self.gridLayout.addWidget(self.kmd_combo, 2, 1, 1, 1)
        self.kmd_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.kmd_status.setPalette(palette)
        self.kmd_status.setObjectName("kmd_status")
        self.gridLayout.addWidget(self.kmd_status, 2, 2, 1, 1)
        self.checkBox_rick = QtWidgets.QCheckBox(self.frame)
        self.checkBox_rick.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_rick.setChecked(True)
        self.checkBox_rick.setObjectName("checkBox_rick")
        self.gridLayout.addWidget(self.checkBox_rick, 2, 4, 1, 1)
        self.rick_combo = QtWidgets.QComboBox(self.frame)
        self.rick_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.rick_combo.setMaxVisibleItems(4)
        self.rick_combo.setObjectName("rick_combo")
        self.rick_combo.addItem("")
        self.rick_combo.addItem("")
        self.rick_combo.addItem("")
        self.rick_combo.addItem("")
        self.gridLayout.addWidget(self.rick_combo, 2, 5, 1, 1)
        self.rick_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.rick_status.setPalette(palette)
        self.rick_status.setObjectName("rick_status")
        self.gridLayout.addWidget(self.rick_status, 2, 6, 1, 1)
        self.checkBox_bch = QtWidgets.QCheckBox(self.frame)
        self.checkBox_bch.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_bch.setObjectName("checkBox_bch")
        self.gridLayout.addWidget(self.checkBox_bch, 3, 0, 1, 1)
        self.bch_combo = QtWidgets.QComboBox(self.frame)
        self.bch_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.bch_combo.setMaxVisibleItems(4)
        self.bch_combo.setObjectName("bch_combo")
        self.bch_combo.addItem("")
        self.bch_combo.addItem("")
        self.bch_combo.addItem("")
        self.bch_combo.addItem("")
        self.gridLayout.addWidget(self.bch_combo, 3, 1, 1, 1)
        self.bch_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.bch_status.setPalette(palette)
        self.bch_status.setObjectName("bch_status")
        self.gridLayout.addWidget(self.bch_status, 3, 2, 1, 1)
        self.checkBox_morty = QtWidgets.QCheckBox(self.frame)
        self.checkBox_morty.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_morty.setChecked(True)
        self.checkBox_morty.setObjectName("checkBox_morty")
        self.gridLayout.addWidget(self.checkBox_morty, 3, 4, 1, 1)
        self.morty_combo = QtWidgets.QComboBox(self.frame)
        self.morty_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.morty_combo.setMaxVisibleItems(4)
        self.morty_combo.setObjectName("morty_combo")
        self.morty_combo.addItem("")
        self.morty_combo.addItem("")
        self.morty_combo.addItem("")
        self.morty_combo.addItem("")
        self.gridLayout.addWidget(self.morty_combo, 3, 5, 1, 1)
        self.morty_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.morty_status.setPalette(palette)
        self.morty_status.setObjectName("morty_status")
        self.gridLayout.addWidget(self.morty_status, 3, 6, 1, 1)
        self.checkBox_doge = QtWidgets.QCheckBox(self.frame)
        self.checkBox_doge.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_doge.setObjectName("checkBox_doge")
        self.gridLayout.addWidget(self.checkBox_doge, 4, 0, 1, 1)
        self.doge_combo = QtWidgets.QComboBox(self.frame)
        self.doge_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.doge_combo.setMaxVisibleItems(4)
        self.doge_combo.setObjectName("doge_combo")
        self.doge_combo.addItem("")
        self.doge_combo.addItem("")
        self.doge_combo.addItem("")
        self.doge_combo.addItem("")
        self.gridLayout.addWidget(self.doge_combo, 4, 1, 1, 1)
        self.doge_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.doge_status.setPalette(palette)
        self.doge_status.setObjectName("doge_status")
        self.gridLayout.addWidget(self.doge_status, 4, 2, 1, 1)
        self.checkBox_dai = QtWidgets.QCheckBox(self.frame)
        self.checkBox_dai.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_dai.setObjectName("checkBox_dai")
        self.gridLayout.addWidget(self.checkBox_dai, 4, 4, 1, 1)
        self.dai_combo = QtWidgets.QComboBox(self.frame)
        self.dai_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.dai_combo.setMaxVisibleItems(4)
        self.dai_combo.setObjectName("dai_combo")
        self.dai_combo.addItem("")
        self.dai_combo.addItem("")
        self.dai_combo.addItem("")
        self.dai_combo.addItem("")
        self.gridLayout.addWidget(self.dai_combo, 4, 5, 1, 1)
        self.dai_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.dai_status.setPalette(palette)
        self.dai_status.setObjectName("dai_status")
        self.gridLayout.addWidget(self.dai_status, 4, 6, 1, 1)
        self.checkBox_dash = QtWidgets.QCheckBox(self.frame)
        self.checkBox_dash.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_dash.setObjectName("checkBox_dash")
        self.gridLayout.addWidget(self.checkBox_dash, 5, 0, 1, 1)
        self.dash_combo = QtWidgets.QComboBox(self.frame)
        self.dash_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.dash_combo.setMaxVisibleItems(4)
        self.dash_combo.setObjectName("dash_combo")
        self.dash_combo.addItem("")
        self.dash_combo.addItem("")
        self.dash_combo.addItem("")
        self.dash_combo.addItem("")
        self.gridLayout.addWidget(self.dash_combo, 5, 1, 1, 1)
        self.dash_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.dash_status.setPalette(palette)
        self.dash_status.setObjectName("dash_status")
        self.gridLayout.addWidget(self.dash_status, 5, 2, 1, 1)
        self.checkBox_rvn = QtWidgets.QCheckBox(self.frame)
        self.checkBox_rvn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_rvn.setObjectName("checkBox_rvn")
        self.gridLayout.addWidget(self.checkBox_rvn, 5, 4, 1, 1)
        self.rvn_combo = QtWidgets.QComboBox(self.frame)
        self.rvn_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.rvn_combo.setMaxVisibleItems(4)
        self.rvn_combo.setObjectName("rvn_combo")
        self.rvn_combo.addItem("")
        self.rvn_combo.addItem("")
        self.rvn_combo.addItem("")
        self.rvn_combo.addItem("")
        self.gridLayout.addWidget(self.rvn_combo, 5, 5, 1, 1)
        self.rvn_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.rvn_status.setPalette(palette)
        self.rvn_status.setObjectName("rvn_status")
        self.gridLayout.addWidget(self.rvn_status, 5, 6, 1, 1)
        self.checkBox_ltc = QtWidgets.QCheckBox(self.frame)
        self.checkBox_ltc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_ltc.setObjectName("checkBox_ltc")
        self.gridLayout.addWidget(self.checkBox_ltc, 6, 0, 1, 1)
        self.ltc_combo = QtWidgets.QComboBox(self.frame)
        self.ltc_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.ltc_combo.setMaxVisibleItems(4)
        self.ltc_combo.setObjectName("ltc_combo")
        self.ltc_combo.addItem("")
        self.ltc_combo.addItem("")
        self.ltc_combo.addItem("")
        self.ltc_combo.addItem("")
        self.gridLayout.addWidget(self.ltc_combo, 6, 1, 1, 1)
        self.ltc_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ltc_status.setPalette(palette)
        self.ltc_status.setObjectName("ltc_status")
        self.gridLayout.addWidget(self.ltc_status, 6, 2, 1, 1)
        self.checkBox_bat = QtWidgets.QCheckBox(self.frame)
        self.checkBox_bat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_bat.setObjectName("checkBox_bat")
        self.gridLayout.addWidget(self.checkBox_bat, 6, 4, 1, 1)
        self.bat_combo = QtWidgets.QComboBox(self.frame)
        self.bat_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.bat_combo.setMaxVisibleItems(4)
        self.bat_combo.setObjectName("bat_combo")
        self.bat_combo.addItem("")
        self.bat_combo.addItem("")
        self.bat_combo.addItem("")
        self.bat_combo.addItem("")
        self.gridLayout.addWidget(self.bat_combo, 6, 5, 1, 1)
        self.bat_status = QtWidgets.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.bat_status.setPalette(palette)
        self.bat_status.setObjectName("bat_status")
        self.gridLayout.addWidget(self.bat_status, 6, 6, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.btn_activate = QtWidgets.QPushButton(self.tab_activate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_activate.sizePolicy().hasHeightForWidth())
        self.btn_activate.setSizePolicy(sizePolicy)
        self.btn_activate.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.btn_activate.setObjectName("btn_activate")
        self.verticalLayout.addWidget(self.btn_activate)
        MainTabs.addTab(self.tab_activate, "")
        self.tab_myorders = QtWidgets.QWidget()
        self.tab_myorders.setObjectName("tab_myorders")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_myorders)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.tab_myorders)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_6.addWidget(self.frame_8, 0, 1, 1, 3)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.orders_table = QtWidgets.QTableWidget(self.tab_myorders)
        self.orders_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orders_table.setProperty("showDropIndicator", False)
        self.orders_table.setDragDropOverwriteMode(False)
        self.orders_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.orders_table.setRowCount(16)
        self.orders_table.setColumnCount(8)
        self.orders_table.setObjectName("orders_table")
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.orders_table.setHorizontalHeaderItem(7, item)
        self.orders_table.horizontalHeader().setCascadingSectionResizes(True)
        self.orders_table.horizontalHeader().setDefaultSectionSize(179)
        self.orders_table.horizontalHeader().setSortIndicatorShown(True)
        self.orders_table.horizontalHeader().setStretchLastSection(True)
        self.orders_table.verticalHeader().setVisible(False)
        self.orders_table.verticalHeader().setDefaultSectionSize(40)
        self.orders_table.verticalHeader().setHighlightSections(True)
        self.orders_table.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_6.addWidget(self.orders_table, 1, 0, 1, 5)
        self.frame_10 = QtWidgets.QFrame(self.tab_myorders)
        self.frame_10.setMinimumSize(QtCore.QSize(930, 0))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_6.addWidget(self.frame_10, 2, 0, 1, 2)
        self.cancel_selected_order_btn = QtWidgets.QPushButton(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_selected_order_btn.sizePolicy().hasHeightForWidth())
        self.cancel_selected_order_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancel_selected_order_btn.setFont(font)
        self.cancel_selected_order_btn.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.cancel_selected_order_btn.setObjectName("cancel_selected_order_btn")
        self.gridLayout_6.addWidget(self.cancel_selected_order_btn, 2, 2, 1, 1)
        self.cancel_all_btn = QtWidgets.QPushButton(self.tab_myorders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_all_btn.sizePolicy().hasHeightForWidth())
        self.cancel_all_btn.setSizePolicy(sizePolicy)
        self.cancel_all_btn.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancel_all_btn.setFont(font)
        self.cancel_all_btn.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.cancel_all_btn.setObjectName("cancel_all_btn")
        self.gridLayout_6.addWidget(self.cancel_all_btn, 2, 3, 1, 2)
        MainTabs.addTab(self.tab_myorders, "")
        self.tab_mytrades = QtWidgets.QWidget()
        self.tab_mytrades.setObjectName("tab_mytrades")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_mytrades)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_44 = QtWidgets.QLabel(self.tab_mytrades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.tab_mytrades)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7.addWidget(self.frame_9, 0, 1, 1, 1)
        self.export_trade_table_btn = QtWidgets.QPushButton(self.tab_mytrades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_trade_table_btn.sizePolicy().hasHeightForWidth())
        self.export_trade_table_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.export_trade_table_btn.setFont(font)
        self.export_trade_table_btn.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.export_trade_table_btn.setObjectName("export_trade_table_btn")
        self.gridLayout_7.addWidget(self.export_trade_table_btn, 0, 2, 1, 1)
        self.trades_table = QtWidgets.QTableWidget(self.tab_mytrades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trades_table.sizePolicy().hasHeightForWidth())
        self.trades_table.setSizePolicy(sizePolicy)
        self.trades_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.trades_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.trades_table.setProperty("showDropIndicator", False)
        self.trades_table.setDragDropOverwriteMode(False)
        self.trades_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.trades_table.setRowCount(16)
        self.trades_table.setColumnCount(8)
        self.trades_table.setObjectName("trades_table")
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.trades_table.setHorizontalHeaderItem(7, item)
        self.trades_table.horizontalHeader().setCascadingSectionResizes(True)
        self.trades_table.horizontalHeader().setDefaultSectionSize(152)
        self.trades_table.horizontalHeader().setSortIndicatorShown(True)
        self.trades_table.horizontalHeader().setStretchLastSection(True)
        self.trades_table.verticalHeader().setVisible(False)
        self.trades_table.verticalHeader().setDefaultSectionSize(40)
        self.trades_table.verticalHeader().setHighlightSections(True)
        self.trades_table.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_7.addWidget(self.trades_table, 1, 0, 1, 3)
        MainTabs.addTab(self.tab_mytrades, "")
        self.tab_orderbook = QtWidgets.QWidget()
        self.tab_orderbook.setObjectName("tab_orderbook")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_orderbook)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_45 = QtWidgets.QLabel(self.tab_orderbook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_4.addWidget(self.label_45)
        self.orderbook_table = QtWidgets.QTableWidget(self.tab_orderbook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderbook_table.sizePolicy().hasHeightForWidth())
        self.orderbook_table.setSizePolicy(sizePolicy)
        self.orderbook_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orderbook_table.setProperty("showDropIndicator", False)
        self.orderbook_table.setDragDropOverwriteMode(False)
        self.orderbook_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.orderbook_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.orderbook_table.setRowCount(16)
        self.orderbook_table.setColumnCount(5)
        self.orderbook_table.setObjectName("orderbook_table")
        item = QtWidgets.QTableWidgetItem()
        self.orderbook_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbook_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbook_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbook_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbook_table.setHorizontalHeaderItem(4, item)
        self.orderbook_table.horizontalHeader().setCascadingSectionResizes(True)
        self.orderbook_table.horizontalHeader().setDefaultSectionSize(207)
        self.orderbook_table.horizontalHeader().setSortIndicatorShown(True)
        self.orderbook_table.horizontalHeader().setStretchLastSection(True)
        self.orderbook_table.verticalHeader().setVisible(False)
        self.orderbook_table.verticalHeader().setDefaultSectionSize(40)
        self.orderbook_table.verticalHeader().setHighlightSections(True)
        self.orderbook_table.verticalHeader().setMinimumSectionSize(40)
        self.verticalLayout_4.addWidget(self.orderbook_table)
        self.frame_11 = QtWidgets.QFrame(self.tab_orderbook)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_11)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sell_combo = QtWidgets.QComboBox(self.frame_11)
        self.sell_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.sell_combo.setObjectName("sell_combo")
        self.horizontalLayout.addWidget(self.sell_combo)
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.buy_combo = QtWidgets.QComboBox(self.frame_11)
        self.buy_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.buy_combo.setObjectName("buy_combo")
        self.horizontalLayout.addWidget(self.buy_combo)
        self.orderbook_buy_btn = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderbook_buy_btn.sizePolicy().hasHeightForWidth())
        self.orderbook_buy_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.orderbook_buy_btn.setFont(font)
        self.orderbook_buy_btn.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.orderbook_buy_btn.setObjectName("orderbook_buy_btn")
        self.horizontalLayout.addWidget(self.orderbook_buy_btn)
        self.verticalLayout_4.addWidget(self.frame_11)
        MainTabs.addTab(self.tab_orderbook, "")
        self.tab_createorder = QtWidgets.QWidget()
        self.tab_createorder.setObjectName("tab_createorder")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_createorder)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.tab_createorder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(1050, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.create_buy_graph_lbl = QtWidgets.QLabel(self.frame_4)
        self.create_buy_graph_lbl.setObjectName("create_buy_graph_lbl")
        self.verticalLayout_6.addWidget(self.create_buy_graph_lbl)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_4)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_6.addWidget(self.graphicsView)
        self.gridLayout_12.addWidget(self.frame_4, 0, 0, 1, 2)
        self.create_order_balance_lbl = QtWidgets.QLabel(self.tab_createorder)
        self.create_order_balance_lbl.setObjectName("create_order_balance_lbl")
        self.gridLayout_12.addWidget(self.create_order_balance_lbl, 2, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_createorder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.create_price_lbl = QtWidgets.QLabel(self.frame_3)
        self.create_price_lbl.setMinimumSize(QtCore.QSize(0, 0))
        self.create_price_lbl.setMaximumSize(QtCore.QSize(125, 40))
        self.create_price_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.create_price_lbl.setObjectName("create_price_lbl")
        self.gridLayout_8.addWidget(self.create_price_lbl, 0, 0, 1, 1)
        self.create_buy_price = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_buy_price.sizePolicy().hasHeightForWidth())
        self.create_buy_price.setSizePolicy(sizePolicy)
        self.create_buy_price.setDecimals(8)
        self.create_buy_price.setMaximum(999999999.99)
        self.create_buy_price.setSingleStep(1e-06)
        self.create_buy_price.setObjectName("create_buy_price")
        self.gridLayout_8.addWidget(self.create_buy_price, 0, 1, 1, 1)
        self.create_amount_lbl = QtWidgets.QLabel(self.frame_3)
        self.create_amount_lbl.setMinimumSize(QtCore.QSize(0, 0))
        self.create_amount_lbl.setMaximumSize(QtCore.QSize(125, 40))
        self.create_amount_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.create_amount_lbl.setObjectName("create_amount_lbl")
        self.gridLayout_8.addWidget(self.create_amount_lbl, 1, 0, 1, 1)
        self.create_buy_amount = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_buy_amount.sizePolicy().hasHeightForWidth())
        self.create_buy_amount.setSizePolicy(sizePolicy)
        self.create_buy_amount.setDecimals(8)
        self.create_buy_amount.setMaximum(9999999999.99)
        self.create_buy_amount.setSingleStep(1e-06)
        self.create_buy_amount.setObjectName("create_buy_amount")
        self.gridLayout_8.addWidget(self.create_buy_amount, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.create_buy_100pct_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_buy_100pct_btn.sizePolicy().hasHeightForWidth())
        self.create_buy_100pct_btn.setSizePolicy(sizePolicy)
        self.create_buy_100pct_btn.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.create_buy_100pct_btn.setFont(font)
        self.create_buy_100pct_btn.setObjectName("create_buy_100pct_btn")
        self.horizontalLayout_2.addWidget(self.create_buy_100pct_btn)
        self.create_buy_75pct_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_buy_75pct_btn.sizePolicy().hasHeightForWidth())
        self.create_buy_75pct_btn.setSizePolicy(sizePolicy)
        self.create_buy_75pct_btn.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.create_buy_75pct_btn.setFont(font)
        self.create_buy_75pct_btn.setObjectName("create_buy_75pct_btn")
        self.horizontalLayout_2.addWidget(self.create_buy_75pct_btn)
        self.create_buy_50pct_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_buy_50pct_btn.sizePolicy().hasHeightForWidth())
        self.create_buy_50pct_btn.setSizePolicy(sizePolicy)
        self.create_buy_50pct_btn.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.create_buy_50pct_btn.setFont(font)
        self.create_buy_50pct_btn.setObjectName("create_buy_50pct_btn")
        self.horizontalLayout_2.addWidget(self.create_buy_50pct_btn)
        self.create_buy_25pct_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_buy_25pct_btn.sizePolicy().hasHeightForWidth())
        self.create_buy_25pct_btn.setSizePolicy(sizePolicy)
        self.create_buy_25pct_btn.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.create_buy_25pct_btn.setFont(font)
        self.create_buy_25pct_btn.setObjectName("create_buy_25pct_btn")
        self.horizontalLayout_2.addWidget(self.create_buy_25pct_btn)
        self.gridLayout_8.addWidget(self.frame_2, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.frame_3, 1, 0, 2, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_createorder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.create_sell_lbl = QtWidgets.QLabel(self.frame_5)
        self.create_sell_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.create_sell_lbl.setObjectName("create_sell_lbl")
        self.gridLayout_10.addWidget(self.create_sell_lbl, 0, 0, 1, 1)
        self.create_sell_combo = QtWidgets.QComboBox(self.frame_5)
        self.create_sell_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.create_sell_combo.setObjectName("create_sell_combo")
        self.gridLayout_10.addWidget(self.create_sell_combo, 0, 1, 1, 1)
        self.creat_buy_lbl = QtWidgets.QLabel(self.frame_5)
        self.creat_buy_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creat_buy_lbl.setObjectName("creat_buy_lbl")
        self.gridLayout_10.addWidget(self.creat_buy_lbl, 1, 0, 1, 1)
        self.create_buy_combo = QtWidgets.QComboBox(self.frame_5)
        self.create_buy_combo.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.create_buy_combo.setObjectName("create_buy_combo")
        self.gridLayout_10.addWidget(self.create_buy_combo, 1, 1, 1, 1)
        self.create_buy_btn = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_buy_btn.sizePolicy().hasHeightForWidth())
        self.create_buy_btn.setSizePolicy(sizePolicy)
        self.create_buy_btn.setMinimumSize(QtCore.QSize(180, 40))
        self.create_buy_btn.setObjectName("create_buy_btn")
        self.gridLayout_10.addWidget(self.create_buy_btn, 2, 0, 1, 2)
        self.gridLayout_12.addWidget(self.frame_5, 1, 1, 2, 1)
        self.frame_13 = QtWidgets.QFrame(self.tab_createorder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(550, 650))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.create_buy_depth_lbl = QtWidgets.QLabel(self.frame_13)
        self.create_buy_depth_lbl.setObjectName("create_buy_depth_lbl")
        self.gridLayout_11.addWidget(self.create_buy_depth_lbl, 0, 0, 1, 1)
        self.create_buy_depth_baserel_lbl = QtWidgets.QLabel(self.frame_13)
        self.create_buy_depth_baserel_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.create_buy_depth_baserel_lbl.setObjectName("create_buy_depth_baserel_lbl")
        self.gridLayout_11.addWidget(self.create_buy_depth_baserel_lbl, 0, 1, 1, 1)
        self.depth_table = QtWidgets.QTableWidget(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.depth_table.setFont(font)
        self.depth_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.depth_table.setAlternatingRowColors(True)
        self.depth_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.depth_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.depth_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.depth_table.setRowCount(24)
        self.depth_table.setObjectName("depth_table")
        self.depth_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.depth_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.depth_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.depth_table.setHorizontalHeaderItem(2, item)
        self.depth_table.horizontalHeader().setDefaultSectionSize(160)
        self.depth_table.horizontalHeader().setMinimumSectionSize(125)
        self.depth_table.horizontalHeader().setStretchLastSection(True)
        self.depth_table.verticalHeader().setVisible(False)
        self.depth_table.verticalHeader().setDefaultSectionSize(30)
        self.depth_table.verticalHeader().setMinimumSectionSize(30)
        self.gridLayout_11.addWidget(self.depth_table, 1, 0, 1, 2)
        self.gridLayout_12.addWidget(self.frame_13, 0, 2, 2, 1)
        MainTabs.addTab(self.tab_createorder, "")
        self.tab_wallet = QtWidgets.QWidget()
        self.tab_wallet.setObjectName("tab_wallet")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_wallet)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wallet_send_frame = QtWidgets.QFrame(self.tab_wallet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_send_frame.sizePolicy().hasHeightForWidth())
        self.wallet_send_frame.setSizePolicy(sizePolicy)
        self.wallet_send_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wallet_send_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wallet_send_frame.setObjectName("wallet_send_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.wallet_send_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.recipient_lbl = QtWidgets.QLabel(self.wallet_send_frame)
        self.recipient_lbl.setMinimumSize(QtCore.QSize(250, 40))
        self.recipient_lbl.setMaximumSize(QtCore.QSize(250, 40))
        self.recipient_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.recipient_lbl.setObjectName("recipient_lbl")
        self.gridLayout_3.addWidget(self.recipient_lbl, 1, 0, 1, 1)
        self.wallet_recipient = QtWidgets.QLineEdit(self.wallet_send_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_recipient.sizePolicy().hasHeightForWidth())
        self.wallet_recipient.setSizePolicy(sizePolicy)
        self.wallet_recipient.setMinimumSize(QtCore.QSize(650, 40))
        self.wallet_recipient.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wallet_recipient.setObjectName("wallet_recipient")
        self.gridLayout_3.addWidget(self.wallet_recipient, 1, 1, 1, 2)
        self.send_amount_lbl = QtWidgets.QLabel(self.wallet_send_frame)
        self.send_amount_lbl.setMinimumSize(QtCore.QSize(250, 40))
        self.send_amount_lbl.setMaximumSize(QtCore.QSize(250, 40))
        self.send_amount_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.send_amount_lbl.setObjectName("send_amount_lbl")
        self.gridLayout_3.addWidget(self.send_amount_lbl, 2, 0, 1, 1)
        self.wallet_amount = QtWidgets.QDoubleSpinBox(self.wallet_send_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_amount.sizePolicy().hasHeightForWidth())
        self.wallet_amount.setSizePolicy(sizePolicy)
        self.wallet_amount.setMinimumSize(QtCore.QSize(0, 40))
        self.wallet_amount.setDecimals(8)
        self.wallet_amount.setObjectName("wallet_amount")
        self.gridLayout_3.addWidget(self.wallet_amount, 2, 1, 1, 1)
        self.wallet_send_btn = QtWidgets.QPushButton(self.wallet_send_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_send_btn.sizePolicy().hasHeightForWidth())
        self.wallet_send_btn.setSizePolicy(sizePolicy)
        self.wallet_send_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.wallet_send_btn.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.wallet_send_btn.setObjectName("wallet_send_btn")
        self.gridLayout_3.addWidget(self.wallet_send_btn, 2, 2, 1, 1)
        self.wallet_address = QtWidgets.QLabel(self.wallet_send_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_address.sizePolicy().hasHeightForWidth())
        self.wallet_address.setSizePolicy(sizePolicy)
        self.wallet_address.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.wallet_address.setFont(font)
        self.wallet_address.setAlignment(QtCore.Qt.AlignCenter)
        self.wallet_address.setOpenExternalLinks(True)
        self.wallet_address.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.wallet_address.setObjectName("wallet_address")
        self.gridLayout_3.addWidget(self.wallet_address, 0, 1, 1, 2)
        self.gridLayout_2.addWidget(self.wallet_send_frame, 1, 1, 1, 1)
        self.wallet_select_frame = QtWidgets.QFrame(self.tab_wallet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_select_frame.sizePolicy().hasHeightForWidth())
        self.wallet_select_frame.setSizePolicy(sizePolicy)
        self.wallet_select_frame.setMinimumSize(QtCore.QSize(400, 560))
        self.wallet_select_frame.setMaximumSize(QtCore.QSize(16777215, 167777))
        self.wallet_select_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wallet_select_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wallet_select_frame.setObjectName("wallet_select_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wallet_select_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wallet_combo = QtWidgets.QComboBox(self.wallet_select_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_combo.sizePolicy().hasHeightForWidth())
        self.wallet_combo.setSizePolicy(sizePolicy)
        self.wallet_combo.setMinimumSize(QtCore.QSize(350, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.wallet_combo.setFont(font)
        self.wallet_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wallet_combo.setStyleSheet("background-color: rgb(114, 159, 207);padding-left:25px;")
        self.wallet_combo.setCurrentText("")
        self.wallet_combo.setMaxVisibleItems(4)
        self.wallet_combo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.wallet_combo.setObjectName("wallet_combo")
        self.verticalLayout_3.addWidget(self.wallet_combo)
        self.wallet_coin_img = QtWidgets.QLabel(self.wallet_select_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_coin_img.sizePolicy().hasHeightForWidth())
        self.wallet_coin_img.setSizePolicy(sizePolicy)
        self.wallet_coin_img.setObjectName("wallet_coin_img")
        self.verticalLayout_3.addWidget(self.wallet_coin_img)
        self.gridLayout_2.addWidget(self.wallet_select_frame, 0, 0, 2, 1)
        self.wallet_balance_frame = QtWidgets.QFrame(self.tab_wallet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_balance_frame.sizePolicy().hasHeightForWidth())
        self.wallet_balance_frame.setSizePolicy(sizePolicy)
        self.wallet_balance_frame.setMinimumSize(QtCore.QSize(0, 300))
        self.wallet_balance_frame.setMaximumSize(QtCore.QSize(16777215, 167777))
        self.wallet_balance_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wallet_balance_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wallet_balance_frame.setObjectName("wallet_balance_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.wallet_balance_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.wallet_balance_lbl = QtWidgets.QLabel(self.wallet_balance_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_balance_lbl.sizePolicy().hasHeightForWidth())
        self.wallet_balance_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.wallet_balance_lbl.setFont(font)
        self.wallet_balance_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.wallet_balance_lbl.setObjectName("wallet_balance_lbl")
        self.gridLayout_5.addWidget(self.wallet_balance_lbl, 0, 0, 1, 1)
        self.wallet_qr_code = QtWidgets.QLabel(self.wallet_balance_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_qr_code.sizePolicy().hasHeightForWidth())
        self.wallet_qr_code.setSizePolicy(sizePolicy)
        self.wallet_qr_code.setMinimumSize(QtCore.QSize(450, 450))
        self.wallet_qr_code.setText("")
        self.wallet_qr_code.setObjectName("wallet_qr_code")
        self.gridLayout_5.addWidget(self.wallet_qr_code, 0, 1, 4, 1)
        self.wallet_balance = QtWidgets.QLabel(self.wallet_balance_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_balance.sizePolicy().hasHeightForWidth())
        self.wallet_balance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.wallet_balance.setFont(font)
        self.wallet_balance.setAlignment(QtCore.Qt.AlignCenter)
        self.wallet_balance.setObjectName("wallet_balance")
        self.gridLayout_5.addWidget(self.wallet_balance, 1, 0, 1, 1)
        self.wallet_locked_by_swaps = QtWidgets.QLabel(self.wallet_balance_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_locked_by_swaps.sizePolicy().hasHeightForWidth())
        self.wallet_locked_by_swaps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.wallet_locked_by_swaps.setFont(font)
        self.wallet_locked_by_swaps.setAlignment(QtCore.Qt.AlignCenter)
        self.wallet_locked_by_swaps.setObjectName("wallet_locked_by_swaps")
        self.gridLayout_5.addWidget(self.wallet_locked_by_swaps, 2, 0, 1, 1)
        self.wallet_usd_value = QtWidgets.QLabel(self.wallet_balance_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet_usd_value.sizePolicy().hasHeightForWidth())
        self.wallet_usd_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.wallet_usd_value.setFont(font)
        self.wallet_usd_value.setAlignment(QtCore.Qt.AlignCenter)
        self.wallet_usd_value.setObjectName("wallet_usd_value")
        self.gridLayout_5.addWidget(self.wallet_usd_value, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.wallet_balance_frame, 0, 1, 1, 1)
        MainTabs.addTab(self.tab_wallet, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_config)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_activate_2 = QtWidgets.QLabel(self.tab_config)
        self.lbl_activate_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_activate_2.sizePolicy().hasHeightForWidth())
        self.lbl_activate_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_activate_2.setFont(font)
        self.lbl_activate_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_activate_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_activate_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_activate_2.setObjectName("lbl_activate_2")
        self.gridLayout_4.addWidget(self.lbl_activate_2, 0, 0, 1, 1)
        self.frame_mm2json = QtWidgets.QFrame(self.tab_config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_mm2json.sizePolicy().hasHeightForWidth())
        self.frame_mm2json.setSizePolicy(sizePolicy)
        self.frame_mm2json.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mm2json.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mm2json.setObjectName("frame_mm2json")
        self.formLayout = QtWidgets.QFormLayout(self.frame_mm2json)
        self.formLayout.setObjectName("formLayout")
        self.frame_12 = QtWidgets.QFrame(self.frame_mm2json)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_seed = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_seed.sizePolicy().hasHeightForWidth())
        self.lbl_seed.setSizePolicy(sizePolicy)
        self.lbl_seed.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_seed.setObjectName("lbl_seed")
        self.verticalLayout_5.addWidget(self.lbl_seed)
        self.btn_generate_seed = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_generate_seed.sizePolicy().hasHeightForWidth())
        self.btn_generate_seed.setSizePolicy(sizePolicy)
        self.btn_generate_seed.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.btn_generate_seed.setObjectName("btn_generate_seed")
        self.verticalLayout_5.addWidget(self.btn_generate_seed)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame_12)
        self.seed_text_input = QtWidgets.QTextEdit(self.frame_mm2json)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seed_text_input.sizePolicy().hasHeightForWidth())
        self.seed_text_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.seed_text_input.setFont(font)
        self.seed_text_input.setReadOnly(False)
        self.seed_text_input.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.seed_text_input.setObjectName("seed_text_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.seed_text_input)
        self.lbl_rpcpass = QtWidgets.QLabel(self.frame_mm2json)
        self.lbl_rpcpass.setObjectName("lbl_rpcpass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_rpcpass)
        self.rpcpass_text_input = QtWidgets.QLineEdit(self.frame_mm2json)
        self.rpcpass_text_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rpcpass_text_input.setObjectName("rpcpass_text_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rpcpass_text_input)
        self.lbl_rpc_ip = QtWidgets.QLabel(self.frame_mm2json)
        self.lbl_rpc_ip.setObjectName("lbl_rpc_ip")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_rpc_ip)
        self.rpc_ip_text_input = QtWidgets.QLineEdit(self.frame_mm2json)
        self.rpc_ip_text_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rpc_ip_text_input.setReadOnly(False)
        self.rpc_ip_text_input.setObjectName("rpc_ip_text_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rpc_ip_text_input)
        self.checkbox_local_only = QtWidgets.QCheckBox(self.frame_mm2json)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.checkbox_local_only.setFont(font)
        self.checkbox_local_only.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkbox_local_only.setChecked(True)
        self.checkbox_local_only.setObjectName("checkbox_local_only")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkbox_local_only)
        self.lbl_binance_key = QtWidgets.QLabel(self.frame_mm2json)
        self.lbl_binance_key.setObjectName("lbl_binance_key")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_binance_key)
        self.binance_key_text_input = QtWidgets.QLineEdit(self.frame_mm2json)
        self.binance_key_text_input.setObjectName("binance_key_text_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.binance_key_text_input)
        self.lbl_binance_secret = QtWidgets.QLabel(self.frame_mm2json)
        self.lbl_binance_secret.setObjectName("lbl_binance_secret")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_binance_secret)
        self.binance_secret_text_input = QtWidgets.QLineEdit(self.frame_mm2json)
        self.binance_secret_text_input.setObjectName("binance_secret_text_input")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.binance_secret_text_input)
        self.lbl_premium = QtWidgets.QLabel(self.frame_mm2json)
        self.lbl_premium.setObjectName("lbl_premium")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_premium)
        self.trade_premium_input = QtWidgets.QDoubleSpinBox(self.frame_mm2json)
        self.trade_premium_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.trade_premium_input.setAlignment(QtCore.Qt.AlignCenter)
        self.trade_premium_input.setObjectName("trade_premium_input")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.trade_premium_input)
        self.lbl_netid = QtWidgets.QLabel(self.frame_mm2json)
        self.lbl_netid.setObjectName("lbl_netid")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_netid)
        self.netid_input = QtWidgets.QSpinBox(self.frame_mm2json)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netid_input.sizePolicy().hasHeightForWidth())
        self.netid_input.setSizePolicy(sizePolicy)
        self.netid_input.setAlignment(QtCore.Qt.AlignCenter)
        self.netid_input.setMaximum(9999)
        self.netid_input.setProperty("value", 9999)
        self.netid_input.setObjectName("netid_input")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.netid_input)
        self.btn_save_config = QtWidgets.QPushButton(self.frame_mm2json)
        self.btn_save_config.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.btn_save_config.setObjectName("btn_save_config")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.btn_save_config)
        self.label_4 = QtWidgets.QLabel(self.frame_mm2json)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.gridLayout_4.addWidget(self.frame_mm2json, 1, 0, 1, 1)
        MainTabs.addTab(self.tab_config, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_log)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lbl_activate_3 = QtWidgets.QLabel(self.tab_log)
        self.lbl_activate_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_activate_3.sizePolicy().hasHeightForWidth())
        self.lbl_activate_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_activate_3.setFont(font)
        self.lbl_activate_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_activate_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_activate_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_activate_3.setObjectName("lbl_activate_3")
        self.gridLayout_9.addWidget(self.lbl_activate_3, 0, 0, 1, 1)
        self.btn_update_logs = QtWidgets.QPushButton(self.tab_log)
        self.btn_update_logs.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.btn_update_logs.setObjectName("btn_update_logs")
        self.gridLayout_9.addWidget(self.btn_update_logs, 2, 1, 1, 1)
        self.btn_export_logs = QtWidgets.QPushButton(self.tab_log)
        self.btn_export_logs.setStyleSheet("background-color: rgb(114, 159, 207)")
        self.btn_export_logs.setObjectName("btn_export_logs")
        self.gridLayout_9.addWidget(self.btn_export_logs, 2, 2, 1, 1)
        self.console_logs = QtWidgets.QPlainTextEdit(self.tab_log)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.console_logs.setFont(font)
        self.console_logs.setReadOnly(True)
        self.console_logs.setPlainText("")
        self.console_logs.setObjectName("console_logs")
        self.gridLayout_9.addWidget(self.console_logs, 1, 0, 1, 3)
        MainTabs.addTab(self.tab_log, "")
        self.create_price_lbl.setBuddy(self.create_buy_price)
        self.create_amount_lbl.setBuddy(self.create_buy_amount)
        self.create_sell_lbl.setBuddy(self.create_sell_combo)
        self.creat_buy_lbl.setBuddy(self.create_buy_combo)

        self.retranslateUi(MainTabs)
        MainTabs.setCurrentIndex(0)
        self.btc_combo.setCurrentIndex(3)
        self.labs_combo.setCurrentIndex(0)
        self.eth_combo.setCurrentIndex(2)
        self.zec_combo.setCurrentIndex(0)
        self.kmd_combo.setCurrentIndex(1)
        self.rick_combo.setCurrentIndex(0)
        self.bch_combo.setCurrentIndex(0)
        self.morty_combo.setCurrentIndex(0)
        self.doge_combo.setCurrentIndex(0)
        self.dai_combo.setCurrentIndex(0)
        self.dash_combo.setCurrentIndex(0)
        self.rvn_combo.setCurrentIndex(0)
        self.ltc_combo.setCurrentIndex(0)
        self.bat_combo.setCurrentIndex(0)
        self.wallet_combo.setCurrentIndex(-1)
        self.btn_activate.clicked.connect(MainTabs.activate_coins)
        self.btn_update_logs.clicked.connect(MainTabs.update_logs)
        MainTabs.currentChanged['int'].connect(MainTabs.prepare_tab)
        self.wallet_send_btn.clicked.connect(MainTabs.send_funds)
        self.buy_combo.activated['int'].connect(MainTabs.show_orderbook)
        self.sell_combo.activated['int'].connect(MainTabs.show_orderbook)
        self.btn_generate_seed.clicked.connect(MainTabs.generate_seed)
        self.btn_save_config.clicked.connect(MainTabs.save_config)
        self.orderbook_buy_btn.clicked.connect(MainTabs.orderbook_buy)
        self.export_trade_table_btn.clicked.connect(MainTabs.export_table)
        self.cancel_all_btn.clicked.connect(MainTabs.cancel_all_orders)
        self.cancel_selected_order_btn.clicked.connect(MainTabs.cancel_order_uuid)
        self.wallet_combo.activated['int'].connect(MainTabs.show_wallet)
        self.create_buy_combo.activated['int'].connect(MainTabs.show_create_orders)
        self.create_sell_combo.activated['int'].connect(MainTabs.show_create_orders)
        self.depth_table.itemSelectionChanged.connect(MainTabs.populate_create_order_vals)
        self.create_buy_25pct_btn.clicked.connect(MainTabs.buy_25pct)
        self.create_buy_50pct_btn.clicked.connect(MainTabs.buy_50pct)
        self.create_buy_100pct_btn.clicked.connect(MainTabs.buy_100pct)
        self.create_buy_75pct_btn.clicked.connect(MainTabs.buy_75pct)
        self.create_buy_btn.clicked.connect(MainTabs.create_setprice)
        QtCore.QMetaObject.connectSlotsByName(MainTabs)

    def retranslateUi(self, MainTabs):
        _translate = QtCore.QCoreApplication.translate
        MainTabs.setWindowTitle(_translate("MainTabs", "Antara Makerbot"))
        self.title_activate.setText(_translate("MainTabs", "Select coins for activation"))
        self.checkBox_btc.setText(_translate("MainTabs", "Bitcoin"))
        self.btc_combo.setCurrentText(_translate("MainTabs", "Buy & sell"))
        self.btc_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.btc_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.btc_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.btc_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.btc_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_labs.setText(_translate("MainTabs", "Labs"))
        self.labs_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.labs_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.labs_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.labs_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.labs_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.labs_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_eth.setText(_translate("MainTabs", "Ethereum"))
        self.eth_combo.setCurrentText(_translate("MainTabs", "Sell"))
        self.eth_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.eth_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.eth_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.eth_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.eth_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_zec.setText(_translate("MainTabs", "Zcash"))
        self.zec_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.zec_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.zec_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.zec_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.zec_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.zec_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_kmd.setText(_translate("MainTabs", "Komodo"))
        self.kmd_combo.setCurrentText(_translate("MainTabs", "Buy"))
        self.kmd_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.kmd_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.kmd_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.kmd_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.kmd_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_rick.setText(_translate("MainTabs", "Rick"))
        self.rick_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.rick_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.rick_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.rick_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.rick_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.rick_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_bch.setText(_translate("MainTabs", "Bitcoin Cash"))
        self.bch_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.bch_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.bch_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.bch_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.bch_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.bch_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_morty.setText(_translate("MainTabs", "Morty"))
        self.morty_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.morty_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.morty_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.morty_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.morty_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.morty_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_doge.setText(_translate("MainTabs", "Dogecoin"))
        self.doge_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.doge_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.doge_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.doge_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.doge_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.doge_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_dai.setText(_translate("MainTabs", "DAI"))
        self.dai_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.dai_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.dai_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.dai_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.dai_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.dai_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_dash.setText(_translate("MainTabs", "Dash"))
        self.dash_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.dash_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.dash_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.dash_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.dash_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.dash_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_rvn.setText(_translate("MainTabs", "Raven"))
        self.rvn_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.rvn_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.rvn_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.rvn_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.rvn_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.rvn_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_ltc.setText(_translate("MainTabs", "Litecoin"))
        self.ltc_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.ltc_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.ltc_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.ltc_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.ltc_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.ltc_status.setText(_translate("MainTabs", "inactive"))
        self.checkBox_bat.setText(_translate("MainTabs", "BAT"))
        self.bat_combo.setCurrentText(_translate("MainTabs", "View only"))
        self.bat_combo.setItemText(0, _translate("MainTabs", "View only"))
        self.bat_combo.setItemText(1, _translate("MainTabs", "Buy"))
        self.bat_combo.setItemText(2, _translate("MainTabs", "Sell"))
        self.bat_combo.setItemText(3, _translate("MainTabs", "Buy & sell"))
        self.bat_status.setText(_translate("MainTabs", "inactive"))
        self.btn_activate.setText(_translate("MainTabs", "Update and activate"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_activate), _translate("MainTabs", "Activate"))
        self.label_2.setText(_translate("MainTabs", "<html><head/><body><p><span style=\" font-size:16pt;\">Open Orders</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainTabs", "Export"))
        item = self.orders_table.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Created"))
        item = self.orders_table.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Sell Coin"))
        item = self.orders_table.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Sell Vol"))
        item = self.orders_table.horizontalHeaderItem(3)
        item.setText(_translate("MainTabs", "Buy Coin"))
        item = self.orders_table.horizontalHeaderItem(4)
        item.setText(_translate("MainTabs", "Buy Price"))
        item = self.orders_table.horizontalHeaderItem(5)
        item.setText(_translate("MainTabs", "Mkt Price"))
        item = self.orders_table.horizontalHeaderItem(6)
        item.setText(_translate("MainTabs", "Premium"))
        item = self.orders_table.horizontalHeaderItem(7)
        item.setText(_translate("MainTabs", "UUID"))
        self.cancel_selected_order_btn.setText(_translate("MainTabs", "Cancel Selected"))
        self.cancel_all_btn.setText(_translate("MainTabs", "Cancel All"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_myorders), _translate("MainTabs", "My Orders"))
        self.label_44.setText(_translate("MainTabs", "<html><head/><body><p><span style=\" font-size:16pt;\">Trade History</span></p></body></html>"))
        self.export_trade_table_btn.setText(_translate("MainTabs", "Export"))
        self.trades_table.setSortingEnabled(True)
        item = self.trades_table.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Date"))
        item = self.trades_table.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Status"))
        item = self.trades_table.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Buy Coin"))
        item = self.trades_table.horizontalHeaderItem(3)
        item.setText(_translate("MainTabs", "Buy Vol"))
        item = self.trades_table.horizontalHeaderItem(4)
        item.setText(_translate("MainTabs", "Sell Coin"))
        item = self.trades_table.horizontalHeaderItem(5)
        item.setText(_translate("MainTabs", "Sell Vol"))
        item = self.trades_table.horizontalHeaderItem(6)
        item.setText(_translate("MainTabs", "Sell Price"))
        item = self.trades_table.horizontalHeaderItem(7)
        item.setText(_translate("MainTabs", "UUID"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_mytrades), _translate("MainTabs", "My Trades"))
        self.label_45.setText(_translate("MainTabs", "<html><head/><body><p><span style=\" font-size:16pt;\">Orderbook</span></p></body></html>"))
        self.orderbook_table.setSortingEnabled(True)
        item = self.orderbook_table.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Sell Coin"))
        item = self.orderbook_table.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Buy Coin"))
        item = self.orderbook_table.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Volume"))
        item = self.orderbook_table.horizontalHeaderItem(3)
        item.setText(_translate("MainTabs", "Sell Price"))
        item = self.orderbook_table.horizontalHeaderItem(4)
        item.setText(_translate("MainTabs", "Mkt Price"))
        self.label.setText(_translate("MainTabs", "Sell:"))
        self.label_3.setText(_translate("MainTabs", "Buy:"))
        self.orderbook_buy_btn.setText(_translate("MainTabs", "Buy Selected"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_orderbook), _translate("MainTabs", "Orderbook"))
        self.create_buy_graph_lbl.setText(_translate("MainTabs", "Graph placeholder"))
        self.create_order_balance_lbl.setText(_translate("MainTabs", "Balance: "))
        self.create_price_lbl.setText(_translate("MainTabs", "Price"))
        self.create_amount_lbl.setText(_translate("MainTabs", "Amount"))
        self.create_buy_100pct_btn.setText(_translate("MainTabs", "100%"))
        self.create_buy_75pct_btn.setText(_translate("MainTabs", "75%"))
        self.create_buy_50pct_btn.setText(_translate("MainTabs", "50%"))
        self.create_buy_25pct_btn.setText(_translate("MainTabs", "25%"))
        self.create_sell_lbl.setText(_translate("MainTabs", "Sell:"))
        self.creat_buy_lbl.setText(_translate("MainTabs", "Buy:"))
        self.create_buy_btn.setText(_translate("MainTabs", "Sell"))
        self.create_buy_depth_lbl.setText(_translate("MainTabs", "Buy / Sell Depth"))
        self.create_buy_depth_baserel_lbl.setText(_translate("MainTabs", "BASE/REL"))
        self.depth_table.setSortingEnabled(True)
        item = self.depth_table.horizontalHeaderItem(0)
        item.setText(_translate("MainTabs", "Price"))
        item = self.depth_table.horizontalHeaderItem(1)
        item.setText(_translate("MainTabs", "Amount"))
        item = self.depth_table.horizontalHeaderItem(2)
        item.setText(_translate("MainTabs", "Value"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_createorder), _translate("MainTabs", "Create Order"))
        self.recipient_lbl.setText(_translate("MainTabs", "Recipient Address:"))
        self.send_amount_lbl.setText(_translate("MainTabs", "Amount"))
        self.wallet_send_btn.setText(_translate("MainTabs", "Send"))
        self.wallet_address.setText(_translate("MainTabs", "<html><head/><body><p><br/></p></body></html>"))
        self.wallet_coin_img.setText(_translate("MainTabs", "<html><head/><body><p><img src=\":/coins/LABS_wallet.png\"/></p></body></html>"))
        self.wallet_balance_lbl.setText(_translate("MainTabs", "Your balance"))
        self.wallet_balance.setText(_translate("MainTabs", "0"))
        self.wallet_locked_by_swaps.setText(_translate("MainTabs", "locked by swaps: 0"))
        self.wallet_usd_value.setText(_translate("MainTabs", "$0 USD"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_wallet), _translate("MainTabs", "Wallet"))
        self.lbl_activate_2.setText(_translate("MainTabs", "Antara Marketmaker Settings"))
        self.lbl_seed.setText(_translate("MainTabs", "Wallet Seed"))
        self.btn_generate_seed.setText(_translate("MainTabs", "Generate"))
        self.lbl_rpcpass.setText(_translate("MainTabs", "RPC Password"))
        self.lbl_rpc_ip.setText(_translate("MainTabs", "RPC IP address"))
        self.rpc_ip_text_input.setPlaceholderText(_translate("MainTabs", "127.0.0.1"))
        self.checkbox_local_only.setText(_translate("MainTabs", "Local only"))
        self.lbl_binance_key.setText(_translate("MainTabs", "Binance API key"))
        self.lbl_binance_secret.setText(_translate("MainTabs", "Binance Secret key"))
        self.lbl_premium.setText(_translate("MainTabs", "Trade Premium (%)"))
        self.lbl_netid.setText(_translate("MainTabs", "NetID"))
        self.btn_save_config.setText(_translate("MainTabs", "Save Settings"))
        self.label_4.setText(_translate("MainTabs", "If you lose your seed, you lose access to your funds. Make sure to keep an offline backup on paper!"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_config), _translate("MainTabs", "Config"))
        self.lbl_activate_3.setText(_translate("MainTabs", "Antara Marketmaker Console Logs"))
        self.btn_update_logs.setText(_translate("MainTabs", "Update"))
        self.btn_export_logs.setText(_translate("MainTabs", "Export"))
        MainTabs.setTabText(MainTabs.indexOf(self.tab_log), _translate("MainTabs", "Logs"))

import coin_icons_rc
